export const TRANSMISSIONS = ['Manual', 'Automática'];
export const FUELS = ['Gasolina', 'Diésel', 'Eléctrico', 'Híbrido'];
export const BODY_TYPES = [
  'Cabriolet','Coupé','Crossover','Furgón','Hatchback','Light Truck',
  'Minibus','Minivan','Monovolumen','Off-Road','Pick-Up','Roadster','Rural','Sedán','SUV','Van',
];

export const VEHICLE_BRANDS = [
  'Acura','Aion','Alfa Romeo','Audi',
  'BAIC','BAW','Bedford','Bestune','BMW','Brilliance','Buggy','BYD','BYD auto',
  'Cfmoto','Chana','Changan','Changhe','Cherry','Chery','Chevrolet','Chevy','Chrysler','Citroën','Compro','Corsa',
  'Daewoo','Dahiatsu','Daihatsu','DFM','DFSK','Dodge','Dongfeng',
  'Effa',
  'FAW','Ferrari','Fiat','Ford','Forland','Foton',
  'G3','Geely','Genérica','GMC','Gonow','Great Wall','Gurgel','GWM',
  'Haima','Haval','Higer','Honda','Hudson','Hummer','Hyundai',
  'Infiniti','Isuzu','Iveco',
  'JAC','Jaguar','Jeep','Jetour','JMC',
  'Kama','Karry','Keyton','Kia','King Star',
  'Lada','Land Rover','Lexus','Lifan','Lincoln','Lotus',
  'Maestro','Mahindra','Maple','Maserati','Maxus','Mazda','Mercedes-Benz','MG','Mini','Mitsubishi','Mobility','Montenegro',
  'Nissan',
  'Omoda','Opel','Orient',
  'Peugeot','Plymouth','Porsche',
  'RAM','Rely','Renault','Rover',
  'Seat','Skoda','Smart','Soueast','SsangYong','Studebaker','Subaru','Suzuki',
  'TATA','Tesla','Toyota','Trike',
  'Victory','Victory Auto','Volkswagen','Volvo',
  'Willys','Wuling',
  'Yasuki',
  'Zna','Zotye','ZxAuto',
];

// Modelos por marca — lista curada de los modelos más comunes
export const VEHICLE_MODELS = {
  'Acura': ['ILX','MDX','RDX','RLX','TLX'],
  'Alfa Romeo': ['147','156','159','Giulia','Giulietta','MiTo','Stelvio'],
  'Audi': ['A1','A3','A4','A5','A6','A7','A8','Q2','Q3','Q5','Q7','Q8','RS3','RS4','RS5','RS6','RS7','S3','S4','S5','S6','TT','e-tron'],
  'BMW': ['116i','118i','120i','125i','130i','318i','320i','325i','328i','330i','335i','418i','420i','430i','520i','525i','528i','530i','540i','550i','M2','M3','M4','M5','M6','X1','X2','X3','X4','X5','X6','X7','Z4'],
  'BYD': ['Atto 3','Dolphin','Han','Seal','Song','Tang'],
  'Chevrolet': ['Aveo','Beat','Blazer','Camaro','Captiva','Colorado','Corvette','Cruze','Equinox','Express','Groove','Malibu','Montana','Onix','Orlando','S10','Silverado','Spark','Suburban','Tahoe','Tracker','Trailblazer','Traverse','Trax'],
  'Chrysler': ['200','300','Grand Voyager','Pacifica','Voyager'],
  'Citroën': ['Berlingo','C1','C2','C3','C4','C5','DS3','DS5','Jumper','Jumpy','Saxo','Xantia','Xsara Picasso'],
  'Daewoo': ['Espero','Kalos','Lacetti','Lanos','Leganza','Matiz','Nubira','Tacuma'],
  'Daihatsu': ['Boon','Charade','Cuore','Feroza','Luxio','Move','Rocky','Sirion','Terios','YRV'],
  'Dodge': ['Attitude','Challenger','Charger','Dakota','Dart','Durango','Grand Caravan','Journey','Neon','Ram','Viper'],
  'Ferrari': ['296','458','488','812','California','F8','GTC4Lusso','LaFerrari','Portofino','Roma','SF90'],
  'Fiat': ['500','500X','Bravo','Cronos','Doblo','Ducato','Fiorino','Idea','Linea','Mobi','Palio','Panda','Punto','Qubo','Scudo','Siena','Stilo','Strada','Tipo','Toro','Uno'],
  'Ford': ['Bronco','EcoSport','Edge','Escape','Expedition','Explorer','F-150','F-250','F-350','Fiesta','Focus','Fusion','Galaxy','Ka','Maverick','Mondeo','Mustang','Puma','Ranger','Territory','Transit','Transit Connect'],
  'Geely': ['Azkarra','Coolray','Emgrand','MK','Okavango','Proton','Tugella'],
  'GMC': ['Acadia','Canyon','Envoy','Sierra','Suburban','Terrain','Yukon'],
  'Great Wall': ['Haval H1','Haval H6','Hover','Peri','Poer','Steed','Wingle'],
  'Haval': ['H1','H2','H4','H6','H9','Jolion'],
  'Honda': ['Accord','Civic','CR-V','Element','Fit','HR-V','Insight','Jazz','Odyssey','Passport','Pilot','Prelude','Ridgeline','Stream'],
  'Hyundai': ['Accent','Azera','Creta','Elantra','Equus','Galloper','Genesis','Grand i10','i10','i20','i30','i40','Ioniq','ix35','Kona','Palisade','Santa Fe','Sonata','Terracan','Tucson','Veloster','Venue'],
  'Infiniti': ['FX35','G35','G37','Q50','Q60','QX50','QX60','QX80'],
  'Isuzu': ['D-Max','Elf','MU-X','Rodeo','Trooper'],
  'JAC': ['J7','Refine','S2','S3','S4','S7','T6','T8','X200'],
  'Jaguar': ['E-Pace','F-Pace','F-Type','I-Pace','S-Type','X-Type','XE','XF','XJ'],
  'Jeep': ['Cherokee','Commander','Compass','Gladiator','Grand Cherokee','Liberty','Patriot','Renegade','Wrangler'],
  'Kia': ['Carnival','Ceed','Cerato','EV6','Forte','Optima','Picanto','Rio','Seltos','Sonet','Sorento','Soul','Sportage','Stinger','Stonic','Telluride'],
  'Land Rover': ['Defender','Discovery','Discovery Sport','Freelander','Range Rover','Range Rover Evoque','Range Rover Sport','Range Rover Velar'],
  'Lexus': ['CT200h','ES350','GS350','IS250','IS350','LX570','NX','RX350','UX'],
  'Lincoln': ['Continental','Corsair','MKC','MKX','MKZ','Navigator'],
  'Maserati': ['Ghibli','GranTurismo','Grecale','Levante','MC20','Quattroporte'],
  'Mazda': ['2','3','6','BT-50','CX-3','CX-30','CX-5','CX-7','CX-9','MX-5','RX-8'],
  'Mercedes-Benz': ['A-Class','B-Class','C-Class','CLA','CLS','E-Class','EQC','G-Class','GLA','GLB','GLC','GLE','GLS','ML','S-Class','SLC','SLK','Sprinter','V-Class','Vito'],
  'MG': ['3','5','6','HS','Marvel R','RX5','ZS'],
  'Mini': ['Clubman','Convertible','Cooper','Countryman','Paceman'],
  'Mitsubishi': ['ASX','Eclipse Cross','Galant','L200','Lancer','Montero','Outlander','Pajero','RVR','Space Star'],
  'Nissan': ['Almera','Frontier','Juke','Kicks','Leaf','Murano','Navara','Note','Pathfinder','Patrol','Qashqai','Sentra','Terrano','Tiida','Titan','Versa','X-Trail'],
  'Opel': ['Astra','Corsa','Grandland','Insignia','Meriva','Mokka','Vectra','Zafira'],
  'Peugeot': ['107','206','207','208','301','308','406','407','408','2008','3008','4007','4008','5008','Expert','Partner'],
  'Porsche': ['718','911','Cayenne','Macan','Panamera','Taycan'],
  'RAM': ['700','1500','2500','3500','ProMaster'],
  'Renault': ['Captur','Clio','Duster','Fluence','Kangoo','Koleos','Kwid','Logan','Master','Megane','Oroch','Sandero','Scenic','Symbol','Trafic','Triber'],
  'Seat': ['Altea','Arona','Ateca','Exeo','Ibiza','Leon','Toledo'],
  'Skoda': ['Fabia','Kamiq','Karoq','Kodiaq','Octavia','Rapid','Scala','Superb'],
  'Subaru': ['Ascent','BRZ','Crosstrek','Forester','Impreza','Legacy','Outback','WRX'],
  'Suzuki': ['Alto','Baleno','Celerio','Dzire','Ertiga','Grand Vitara','Ignis','Jimny','S-Cross','Swift','Vitara','XL7'],
  'Tesla': ['Model 3','Model S','Model X','Model Y','Roadster'],
  'Toyota': ['4Runner','86','Avalon','Avanza','C-HR','Camry','Corolla','Corolla Cross','FJ Cruiser','Fortuner','GR86','Hilux','Land Cruiser','Prado','Prius','ProAce','RAV4','Rush','Sequoia','Sienna','Supra','Tacoma','Tundra','Vios','Yaris','Yaris Cross'],
  'Volkswagen': ['Amarok','Caddy','Caravelle','Crafter','Fox','Gol','Golf','ID.4','Jetta','Passat','Polo','Saveiro','T-Cross','T-Roc','Taos','Teramont','Tiguan','Touareg','Touran','Transporter','Up','Virtus','Vento'],
  'Volvo': ['C30','C40','S60','S90','V40','V60','V90','XC40','XC60','XC90'],
};
